# Python review

## goals:
- recall basic python vocabulary
- practice markdown

**library**: a collection of code that we can use to perform specific tasks in our programs

**NumPy**
- core library for numerical computing in python
- many other libraries use NumPu arrays as building bloacks
- computations on NumPy are optimized for speed and memory usage

import NumPy with **standard abbreviation**

In [2]:
import numpy as np

## Variables

**variable** is a name we assign a particular object in Python
example:


In [3]:
# assign a small array to a variable a
a = np.array( [ [1,1,2], [3,5,8] ] )

In [4]:
# run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# use `print()` to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
 **object** is a bundle of *properties* and *actions* about something specific
example:
object: data frame
properties: number rows, names of th columns, date created

actions: selecting a specific row, adding a new column

A *variable* is the name we give a specific object, and the same object can be referenced by different variables

In practice , we can use variable and object interchangeably most of the time 