# Python review

## goals:
- recall basic python vocabulary
- practice markdown

**library**: a collection of code that we can use to perform specific tasks in our programs

**NumPy**
- core library for numerical computing in python
- many other libraries use NumPu arrays as building bloacks
- computations on NumPy are optimized for speed and memory usage

import NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables

**variable** is a name we assign a particular object in Python
example:


In [2]:
# assign a small array to a variable a
a = np.array( [ [1,1,2], [3,5,8] ] )

In [3]:
# run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# use `print()` to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
 **object** is a bundle of *properties* and *actions* about something specific
example:
object: data frame
properties: number rows, names of th columns, date created

actions: selecting a specific row, adding a new column

A *variable* is the name we give a specific object, and the same object can be referenced by different variables

In practice , we can use variable and object interchangeably most of the time 

## Types

Every object in Python has a **type**, the type tells us what kinfd of object it is
We can also call the type of an object, the **class** of an object ad they both mean what kind of object we have

In [5]:
print(a)

# Check the type/class of a variable/ object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0, 0])

# Check the ype on an entry on the array by indexing
type(a[0,0]) # returns the entry in the first row in the first column

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard python integer type. This is telling us that 1 is an intefer stored as a 64-bit number. 

In [10]:
# Access the 2nd row and 2nd column space
a[1,1]

5


## Functions
`print` was our first example of a python **function**
functions take in a set of **arguments** and those arguments create an **output**
argument = parameter
we can ask information about a function by executing `?function`

In [11]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**. 

A function has two types of arguments

- **non-optional**: arguments you need to specify for the function to do something
- **optional**: arguments that are pre-filled with a default argument, which you can override
Optional arguments appear inside the parentheses in the form `optional_argument=default_value`

In [12]:
print('changing the default end argument')

changing the default end argument


In [13]:
print('changing the default end argument', end=' :)')

changing the default end argument :)

## Attributes and methods
an object in python has both 

- **attributes**: a property of an object, some piece of information about it
- **method**: a function that can act on the object

## Check in
Fish attributes: length, color, species
Fish methods: bite_lure(), swim(), die()

**Examples** 
attributes for `numpy.arrays`

In [15]:
# look at how many rows and columns
a.shape

(2, 3)

In [16]:
type(a.shape)

tuple

In [18]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [17]:
# Methods examples
# min() returns the minimum value along the specified axis
# find the min values along columns
# axis is an optional parameter here- default just finds the single smallest value in the data
a.min(axis=0)

array([1, 1, 2])

In [19]:
a.min()

1

remember: methods are functions associated with an object

In [20]:
type(a.min)

builtin_function_or_method

## Exercise 
1. read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional agument? Why?

2. create two new variables ine with the integer value 77 and another one with the string 99.

3. Use your variables to print '77%99%77' by changing the value of one of th earguments in print

In [25]:
a = '77'
b= '99'
print(a, b, a, sep = '%')
print('77', '99', '77', sep = '%')
?print

77%99%77
77%99%77


Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [27]:
type()
# sep is an optional string argument

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method